### PR TITLE
Include an indication to which image is referred to

### PR DESCRIPTION
**Pull request by csoutham**
Thought this would be an useful feature to pull our image source along with alt tag.

### CODE REVIEW

**Comment by csoutham** [comment]
On review, I can see presenting the alts[] as a nested array of results throws the metric analysis into thinking it's correct when it's not. I'm unsure how to fix this at present.

**Comment by grgk** [comment]
I don't think this will be good solution as it will change the output format, so it could break some applications implementing it that way. I think it will be much better to change the hard-coded Parser to allow to be injected, so everyone can implement own Parser. Then in your case you can simply extend the existing Parser overwriting only that one method. What do you think?

**Comment by grgk** [comment]
@csoutham, it is now rebuilt in such a way that you can use your own parser, as mentioned above. Please check the example here: https://github.com/grgk/seo-analyzer/blob/master/examples/analyze_file_with_custom_parser.php

**Comment by csoutham** [comment]
Nice one thanks, that's a really nice feature :)

**Pull request closed without merging**
